set(CPACK_PACKAGE_NAME "${APPLICATION_NAME}")
set(CPACK_PACKAGE_VENDOR "${ORGANIZATION_NAME}")

set(CPACK_PACKAGE_VERSION_MAJOR "${APPLICATION_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${APPLICATION_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${APPLICATION_VERSION_PATCH}")

set(CPACK_PACKAGE_VERSION "${APPLICATION_VERSION}")
set(CPACK_PACKAGE_CONTACT "sadylan@gmail.com")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${APPLICATION_DESCRIPTION}")
set(CPACK_PACKAGE_EXECUTABLES audioreceiver "AudioReceiver")

set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE.md")
set(CPACK_RESOURCE_FILE_README "${PROJECT_SOURCE_DIR}/README.md")
#set(CPACK_RESOURCE_FILE_WELCOME "${PROJECT_SOURCE_DIR}/WELCOME.txt")

if (UNIX AND NOT APPLE)
    set(CPACK_GENERATOR "DEB")

    execute_process(COMMAND dpkg --print-architecture
            OUTPUT_VARIABLE CPACK_DEBIAN_PACKAGE_ARCHITECTURE
            OUTPUT_STRIP_TRAILING_WHITESPACE)

    set(CPACK_DEBIAN_PACKAGE_SECTION "misc")
    set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
    set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS TRUE)

    set(CPACK_PACKAGE_FILE_NAME "audioreceiver-${CPACK_PACKAGE_VERSION}-${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}")
elseif (WIN32)
    set(CPACK_GENERATOR "WIX")

    set(CPACK_WIX_UPGRADE_GUID "2B86AD48-AD9C-4597-83DC-A15035F0C31D")
    set(CPACK_WIX_PROPERTY_ARPHELPLINK "https://github.com/sardylan/audioreceiver")
    #    set(CPACK_WIX_PROPERTY_ARPSIZE "0")

    set(CPACK_PACKAGE_INSTALL_DIRECTORY "AudioReceiver ${APPLICATION_VERSION}")
    set(CPACK_PACKAGE_ICON "icons/application/icon.ico")

    set(CPACK_PACKAGE_FILE_NAME "audioreceiver-${CPACK_PACKAGE_VERSION}")
elseif (APPLE)
    #    set(CPACK_GENERATOR "OSXX11")
    set(CPACK_GENERATOR "Bundle")

    set(CPACK_PACKAGE_FILE_NAME "audioreceiver-${CPACK_PACKAGE_VERSION}")
endif ()

include(CPack)

cpack_add_component(audioreceiver
        DISPLAY_NAME "AudioReceiver"
        DESCRIPTION "${CPACK_PACKAGE_DESCRIPTION_SUMMARY}"
        REQUIRED)

if (WIN32 OR APPLE)
    cpack_add_component(qtlibs
            DISPLAY_NAME "Qt libs"
            DESCRIPTION "Qt5 libraries"
            DEPENDS audioreceiver)
endif ()
