name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: sudo apt install qt5-default qtmultimedia5-dev libqt5svg5-dev mesa-common-dev
      - name: Configure
        run: mkdir build && cd build && cmake ..
      - name: Make
        run: cd build && make
      - name: Make check
        run: cd build && make check
      - name: Make distcheck
        run: cd build && make distcheck
