name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  linux:
    name: "Linux Ubuntu"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare OS
        run: sudo add-apt-repository ppa:beineri/opt-qt-5.14.2-bionic && sudo apt-get update && sudo apt install qt514-meta-full mesa-common-dev libgl1-mesa-dev libfftw3-3 libfftw3-dev
#      - name: Create 3rdparty directory
#        run: mkdir -p 3rdparty
#      - name: FFTW3 Download
#        run: cd 3rdparty && wget http://www.fftw.org/fftw-3.3.8.tar.gz && tar xf fftw-3.3.8.tar.gz
#      - name: FFTW3 Configure
#        run: cd 3rdparty && mkdir fftw-3.3.8-build fftw-3.3.8-install && cd fftw-3.3.8-build && cmake ../fftw-3.3.8 -DCMAKE_INSTALL_PREFIX=../fftw-3.3.8-install -DENABLE_SSE=TRUE -DENABLE_SSE2=TRUE -DENABLE_AVX=TRUE -DENABLE_AVX2=TRUE -DENABLE_THREADS=TRUE -DWITH_COMBINED_THREADS=TRUE
#      - name: FFTW3 Build
#        run: cd 3rdparty/fftw-3.3.8-build && make -j
#      - name: FFTW3 Test
#        run: cd 3rdparty/fftw-3.3.8-build && make -j test
#      - name: FFTW3 Install
#        run: cd 3rdparty/fftw-3.3.8-build && make -j install
      - name: Configure
        run: source /opt/qt514/bin/qt514-env.sh && mkdir build && cd build && cmake .."
      - name: Make
        run: source /opt/qt514/bin/qt514-env.sh && cd build && make
      - name: Tests
        run: source /opt/qt514/bin/qt514-env.sh && cd build && make test
      - name: Package
        run: source /opt/qt514/bin/qt514-env.sh && cd build && make package
  windows:
    name: "Windows"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.0
      - name: Create 3rdparty directory
        run: mkdir -p 3rdparty
      - name: FFTW3 Download
        run: cd 3rdparty && curl -o fftw-3.3.8.zip ftp://ftp.fftw.org/pub/fftw/fftw-3.3.8.zip && 7z.exe x fftw-3.3.8.zip
      - name: FFTW3 Configure
        run: cd 3rdparty && mkdir fftw-3.3.8-build && mkdir fftw-3.3.8-install && cd fftw-3.3.8-build && cmake ../fftw-3.3.8 -DCMAKE_INSTALL_PREFIX=../fftw-3.3.8-install -DCMAKE_C_FLAGS="-DWITH_OUR_MALLOC -O3" -DCMAKE_CXX_FLAGS="-DWITH_OUR_MALLOC -O3" -DENABLE_SSE=TRUE -DENABLE_SSE2=TRUE -DENABLE_AVX=TRUE -DENABLE_AVX2=TRUE -DENABLE_THREADS=TRUE -DWITH_COMBINED_THREADS=TRUE
      - name: FFTW3 Build
        run: cd 3rdparty/fftw-3.3.8-build && msbuild fftw.sln
      - name: FFTW3 Test
        run: cd 3rdparty/fftw-3.3.8-build && msbuild RUN_TESTS.vcxproj
      - name: FFTW3 Install
        run: cd 3rdparty/fftw-3.3.8-build && msbuild INSTALL.vcxproj
      - name: Configure
        run: mkdir build && cd build && cmake .. -DFFTW_ROOT="../fftw-3.3.8-install"
      - name: Make
        run: cd build && msbuild audioreceiver.sln
      - name: Make check
        run: cd build && msbuild RUN_TESTS.vcxproj
#  macos:
#    runs-on: macos-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Prepare OS
#        run: sudo apt install qt5-default qtmultimedia5-dev libqt5svg5-dev mesa-common-dev
#      - name: Create 3rdparty directory
#        run: mkdir -p 3rdparty
#      - name: FFTW3 Download
#        run: cd 3rdparty && wget http://www.fftw.org/fftw-3.3.8.tar.gz && tar xf fftw-3.3.8.tar.gz
#      - name: FFTW3 Configure
#        run: cd 3rdparty && mkdir fftw-3.3.8-build fftw-3.3.8-install && cd fftw-3.3.8-build && cmake ../fftw-3.3.8 -DCMAKE_INSTALL_PREFIX=../fftw-3.3.8-install -DENABLE_SSE=TRUE -DENABLE_SSE2=TRUE -DENABLE_AVX=TRUE -DENABLE_AVX2=TRUE -DENABLE_THREADS=TRUE -DWITH_COMBINED_THREADS=TRUE
#      - name: FFTW3 Build
#        run: cd 3rdparty/fftw-3.3.8-build && make -j
#      - name: FFTW3 Install
#        run: cd 3rdparty/fftw-3.3.8-build && make -j install
#      - name: Configure
#        run: mkdir build && cd build && cmake .. -DFFTW3_DIR="${{ github.workspace }}/3rdparty/fftw-3.3.8-install/lib/cmake/fftw3"
#      - name: Make
#        run: cd build && make
#      - name: Make check
#        run: cd build && make check
#      - name: Make distcheck
#        run: cd build && make distcheck
