name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
#        os: [windows-latest, macOS-latest, ubuntu-latest, ubuntu-16.04]
        os: [ubuntu-latest]
        version: ["5.15.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: sudo apt install qt5-default mesa-common-dev
      - name: Configure
        working-directory: ${{ runner.workspace }}/build
        run: cmake ${{ runner.workspace }}
      - name: Make
        working-directory: ${{ runner.workspace }}/build
        run: make
      - name: Make check
        working-directory: ${{ runner.workspace }}/build
        run: make check
      - name: Make distcheck
        working-directory: ${{ runner.workspace }}/build
        run: make distcheck
